### ISSUE TITLE
User select ticker

### ISSUE THREAD

**Issue by ZachGlassman** [thedataincubator/stockpredict#11]
We want the user to select the ticker in a form instead of hardcoding it in.  We need a front page will a bit of user interaction.  It would also be useful to select a relevant date range and prediction period.

**Comment by Nomdecyber** [comment]
This is partially addressed in commit 8e18ad77e03d332b7434dbe7da50f45cac14b602. We should also consider adding this to the portfolio route.

**Comment by ZachGlassman** [comment]
I think this is addressed for now.  We probably want to break out the selection into a componet that can be applied accross multiple pages.
