### ISSUE TITLE
package versions

### ISSUE THREAD

**Issue by adrianyi** [thedataincubator/stockpredict#17]
I ran into some issues in local testing because of inconsistent package versions for Bokeh...

It would be nice to have package versions specified in requirement files.
Also, default bokeh version is defined as 0.12.7 in app.py, but the D.O. boxes use 0.12.4. It might be better for to use 4 as default.

**Comment by ZachGlassman** [comment]
I would prefer the newer version as it has documentation.  We should be using a virtual environment for this anyway.  But :+1: for specifying versions!

**Comment by eamander** [comment]
To put together a proper list of package specifications, I would like to try to run the whole app on a local server. I don't know what "PROPHET_URL" is supposed to be, so I am having some difficulty doing this. Can you explain what that is?

**Comment by ZachGlassman** [comment]
`PROPHET_URL` is the url to the time series model.  If you want to run locally or on your DO box, you can run `PR_TEST_API.ipynb` and point this URL to the localhost port where the flask app defined in that notebook is running.

**Comment by eamander** [comment]
Do we want to specify versions for packages we're not using yet? I can run everything without error so far. My thoughts are to specify all of the package versions that we're actively using, and only specify further versions when they are used.  

Either that or have a short discussion about some of the modules.:

nomlk, dill, nose (unless it is incorporated automatically into unittest somehow), and mock. 

I understand gunicorrn is included mostly to be implemented on Heroku, so I am welcome to suggestions about the version we should be implementing.

**Comment by ZachGlassman** [comment]
`nomlk` allows us to not install `mkl` which is an optimization library affecting the numpy stack.  We don't want it here because its pretty heavy and not really necessary.  `dill` is something I don't believe we need at the moment.  `nose` we are using to run tests (see `.travis.yml`) and `mock` is also important for that.  

Please specify versions (preferably newest possibly) for all packages and get rid of `dill` if possible.

**Comment by ZachGlassman** [comment]
One easy way to get the versions is to install the requirements (`conda-requirements.txt` with conda and `requirements.txt`with pip) locally without versioning things and see what versions are installed.  Then lock the packages to these version.  You might also want to check out `Pipenv` which is newer tool.
