### ISSUE TITLE
Quandl

### ISSUE THREAD

**Issue by ZachGlassman** [thedataincubator/stockpredict#5]
Instead of loading the data from file, we should be querying from Quandl.  We could also build this into the backend service, so lets try to keep this very modular so we can move it back to that service if we would like.

**Comment by adrianyi** [comment]
I can take this one :P

I plan on adding a function that takes `ticker name`, `quandl key`, `value` (such as open), and `# of days`.
The function will return a pandas dataframe with columns `ds` & `y` (corresponding to date & value).

I was thinking of changing create_app function to take in another quandl_api_key argument, so all keys are nicely organized in app.py.

I'll add minimal error handling for now (in the case request to Quandl fails) and simply return an empty pandas dataframe... I'm not sure how that works with the next steps... maybe someone else can help with error handling?

**Comment by ZachGlassman** [comment]
I like the first two.  Instead of an empty dataframe, lets use some exceptions here.  We don't want to fail silently and have an empty dataframe.  But for now, lets be simple and define a `QuandlException` which gets raised on any api error.
